name: Run Integration Tests

on:
  # Schedule to run every day at 12 midnight Pacific Time
  schedule:
    - cron: '0 7 * * *'

  # Allow manual triggering of this workflow from the GitHub Actions UI
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: mbstring, dom, curl
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Integration Tests
      run: ./vendor/bin/phpunit --testsuite Integration
